Repository AzureAD/microsoft-identity-web, pull requests merged in 2020-07, with the labels that each got.

#279 changes to the cachekey to use tokenNotificationArgs
  src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
  src/Microsoft.Identity.Web/Microsoft.Identity.Web.xml
  src/Microsoft.Identity.Web/TokenAcquisition.cs
  src/Microsoft.Identity.Web/TokenCacheProviders/Distributed/MsalDistributedTokenCacheAdapter.cs
  src/Microsoft.Identity.Web/TokenCacheProviders/IMsalTokenCacheProvider.cs
  src/Microsoft.Identity.Web/TokenCacheProviders/InMemory/MsalMemoryTokenCacheProvider.cs
  src/Microsoft.Identity.Web/TokenCacheProviders/MsalAbstractTokenCacheProvider.cs
  src/Microsoft.Identity.Web/TokenCacheProviders/Session/MsalSessionTokenCacheProvider.cs
  tests/B2CWebAppCallsWebApi/Client/appsettings.json
  tests/Microsoft.Identity.Web.Test.Common/TestHelpers/MsalTestTokenCacheProvider.cs
  tests/Microsoft.Identity.Web.Test.Integration/AcquireTokenForAppIntegrationTests.cs
  tests/Microsoft.Identity.Web.Test.LabInfrastructure/Microsoft.Identity.Web.Test.LabInfrastructure.csproj
Labels: merge after MSAL .NET release

#304 Improves the migration aid
  src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebApiServiceCollectionExtensions.cs
  src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebAppAuthenticationBuilderExtensions.cs
  src/Microsoft.Identity.Web/MigrationAid/Obsolete-WebAppServiceCollectionExtensions.cs
Labels: supportability

#311 update to msal 4.16.1
  src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
  tests/Microsoft.Identity.Web.Test.LabInfrastructure/Microsoft.Identity.Web.Test.LabInfrastructure.csproj
Labels: merge after MSAL .NET release

#363 0.2.1-preview changelog
  changelog.txt
Labels: do not merge before Ms.Id.Web releases

#371 update to msal 4.17.0
  src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
  tests/Microsoft.Identity.Web.Test.LabInfrastructure/Microsoft.Identity.Web.Test.LabInfrastructure.csproj
Labels: merge after MSAL .NET release
